wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683529484.400688
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.8.16
      5: 0.15.0
      8:
      - 1
      - 5
